stages:
  - release

release:
  stage: release
  image: docker:stable
  variables:
    CI_REGISTRY: hub.infervision.com
    CI_REGISTRY_IMAGE: $CI_REGISTRY/dev/cloudms-web
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY
  script:
    - if [ "master" == "$CI_COMMIT_REF_NAME" ]; then export CI_COMMIT_REF_NAME="latest"; fi
    - echo $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - tags